title: "Md. Saidul Islam — Materials ML & Simulation"
description: "Portfolio: materials science, ML for band gap prediction, simulation (FEM/COMSOL), and reproducible research."
url: "https://submerged-in-matrix.github.io"

# Theme (built-in, zero setup)
theme: jekyll-theme-minimal

# Navigation links
nav:
  - name: About
    link: /
  - name: Projects
    link: /projects
  - name: Publications
    link: /publications
  - name: Resume
    link: /assets/resume/Resume_MD_Saidul_Islam.pdf
  - name: Contact
    link: /contact

# Socials
github_username: submerged-in-matrix
linkedin: "https://www.linkedin.com/in/"  # add your handle
email: "your.email@example.com"

# Markdown options
markdown: kramdown
kramdown:
  input: GFM
