# --- site basics ----
title: "Md. Saidul Islam — Materials ML & Simulation"
description: "Materials scientist & simulation engineer for High-Throughput Materials Development and AI-assisted simulation."
url: "https://submerged-in-matrix.github.io"


# Use a simple built-in theme (CSS overrides it)
theme: jekyll-theme-minimal


# Navigation (order matters)
nav:
- name: About
link: /
- name: Masters Thesis
link: /masters-thesis
- name: Bachelor Thesis
link: /bachelor-thesis
- name: Projects
link: /projects
- name: E-Learning
link: /e-learning
- name: Profiles
link: /profiles
- name: Contact
link: /contact


# Socials / meta
github_username: submerged-in-matrix
email: "sayeed.shahriar@gmail.com"
linkedin: "https://www.linkedin.com/in/shahriar-sayeed/"


markdown: kramdown
kramdown:
input: GFM
