# --- site basics ----
title: "Md. Saidul Islam   
Computational Materials Engineer"
description: "Materials scientist & simulation engineer for High-Throughput Materials Development and AI-assisted simulation."
url: "https://submerged-in-matrix.github.io"

# Use a simple built-in theme (CSS overrides it)
theme: jekyll-theme-minimal

# Navigation (order matters)
nav:
  - name: About
    link: /
  - name: Masters Thesis
    link: /masters-thesis
  - name: Projects
    link: /projects
  - name: E-Learning
    link: /e-learning
  - name: Poster/Publication
    link: /poster-publication
  - name: Resume
    link: /assets/resume/Resume_MD_Saidul_Islam.pdf
  - name: Documents
    link: /documents
  - name: Profiles
    link: /profiles
  - name: Contact
    link: /contact
  - name: Recommendation
    link: /recommendation


# Socials / meta
github_username: submerged-in-matrix
email: "sayeed.shahriar@gmail.com"
linkedin: "https://www.linkedin.com/in/shahriar-sayeed/"

markdown: kramdown
kramdown:
  input: GFM
